services:
  - type: web
    name: kisan-saathi-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: False
    healthCheckPath: /api/health
    autoDeploy: true
    region: oregon
    plan: free
    scaling:
      minInstances: 0
      maxInstances: 1 